from enum import Enum

class RideState(str, Enum):
    # Simulation
    REQUESTED = "REQUESTED"
    PENDING = "PENDING"
    PICKUP = "PICKUP"
    ON_ROAD = "ON_ROAD"
    END = "END"
    CANCELED = "CANCELED"
    CANCELED_ON_PICKUP = "CANCELED_ON_PICKUP"
    CANCELED_ON_ROAD = "CANCELED_ON_ROAD"
    NOT_SERVED = "NOT SERVED"
    SIMULATION_ERROR = "SIMULATION ERROR"
