from enum import Enum

class EventType(str, Enum):
    DRIVER_GENERATION = "DRIVER_GENERATION"
    DRIVER_STOP_WORK = "DRIVER_STOP_WORK"
    SLOW_DOWN_SPEED = "SLOW_DOWN_SPEED"
    SPEED_UP = "SPEED_UP"
    RIDE_LENGTH = "RIDE_LENGTH"
