from enum import Enum

class DriverRemotion(str, Enum):
    ROUTE_NOT_FOUND = "ROUTE_NOT_FOUND"
    SET_ROUTE_FAILED = "SET_ROUTE_FAILED"
    TRACI_FORCED_REMOTION = "TRACI_FORCED_REMOTION"
    STOP_WORK = "STOP_WORK"
    UNPROFITABLE_SURGE_MULTIPLIER = "UNPROFITABLE_SURGE_MULTIPLIER"
    TRACI_FORCED_CUSTOMER_REMOTION_DURING_RIDE = "TRACI_FORCED_CUSTOMER_REMOTION_DURING_RIDE"